Feature/support calendar events
BugBuster1701/contao-visitors-bundle pull request #120
Opened 2022-06-13 08:02 UTC by baumannsven

2022-06-22 05:41 UTC, baumannsven commented
@BugBuster1701 Do have seen this?

2022-07-08 08:46 UTC, BugBuster1701 commented
Not until today. I was ill and will look at it in the next few days. Thank you.

2022-07-12 22:09 UTC, BugBuster1701 requested changes
Einige News müssten noch zu Events umbenannt werden

2022-07-12 22:09 UTC, BugBuster1701 commented on src/Resources/contao/classes/ModuleVisitorStatEventsCounter.php
> +    public function generateNewsVisitHitDays($VisitorsID, $limit = 10, $parse = true, $days=7)
`generateEventsVisitHitDays` sollte das doch heißen, oder?

2022-07-12 22:09 UTC, BugBuster1701 commented on src/Resources/contao/modules/ModuleVisitorStat.php
> +                $arrVisitorsEventsVisitHitsDays[$intAnzCounter]      = ModuleVisitorStatEventsCounter::getInstance()->generateNewsVisitHitDays($objVisitorsID, 20, true, 7);
`generateEventsVisitHitDays`

2022-07-12 22:09 UTC, BugBuster1701 commented on src/Resources/contao/templates/mod_visitors_be_stat_partial_eventsvisithitdays.html5
> +<!-- NewsHitDays::start -->
EventsHitDays

2022-07-12 22:09 UTC, BugBuster1701 commented on src/Resources/contao/templates/mod_visitors_be_stat_partial_eventsvisithitdays.html5
> +<!-- NewsHitDays::stop -->
EventsHitDays

2022-07-12 22:09 UTC, BugBuster1701 commented on src/Resources/contao/templates/mod_visitors_be_stat_partial_eventsvisithittop.html5
> +<!-- NewsHitTop::start -->
EventsHitTop

2022-07-12 22:09 UTC, BugBuster1701 commented on src/Resources/contao/templates/mod_visitors_be_stat_partial_eventsvisithittop.html5
> +<!-- NewsHitTop::stop -->
EventsHitTop

2022-07-12 22:09 UTC, BugBuster1701 commented on src/Resources/contao/classes/ModuleVisitorStatEventsCounter.php
> +    public function generateNewsVisitHitDays($VisitorsID, $limit = 10, $parse = true, $days=7)
generateEventsVisitHitDays

2022-07-30 08:28 UTC, merged